export default {
  GET_AIRPORTS: 'GET_AIRPORTS',
  GET_AIRPORT_TYPE_LIST: 'GET_AIRPORT_TYPE_LIST',
  GET_AIRPORT_LIST_LOADED: 'GET_AIRPORT_LIST_LOADED',
  GET_AIRCRAFT_LIST_LOADED: 'GET_AIRCRAFT_LIST_LOADED',
};
