export default {
  GET_SITES: 'GET_SITES',
  GET_AIRPORTS_LIST: 'GET_AIRPORTS_LIST',
  GET_SITE_LIST_LOADED: 'GET_SITE_LIST_LOADED',
  GET_AIRPORT_LIST_LOADED: 'GET_AIRPORT_LIST_LOADED',
  SITE_UPDATED: 'SITE_UPDATED',
  SITE_LOADED: 'SITE_LOADED',
};
