export default {
  GET_ROLES: 'GET_ROLES',
  GET_USERS: 'GET_USERS',
  GET_SITES: 'GET_SITES',
  UPDATE_LAST_LOGGED_IN_TIME: 'UPDATE_LAST_LOGGED_IN_TIME',
  GET_ROLE_LIST_LOADED: 'GET_ROLE_LIST_LOADED',
  GET_SITE_LIST_LOADED: 'GET_USER_LIST_LOADED',
  GET_SITES_LIST: 'GET_SITES_LIST',
};
