import constants from '../../constants';

export const styles = {
  marginContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100vw',
    height: '100vh',
    backgroundColor: '#F5F6F9',
    paddingLeft: '15vw',
  },
  container: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    width: '70vw',
    height: '75vh',
    marginTop: 135,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  box: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  reportsIcon: {
    height: 110,
  },
  title: {
    color: '#404040',
    fontSize: 26,
    fontFamily: constants.FuturaBook,
  },

  reportButton: {
    borderRadius: 0,
    paddingRight: 40,
    paddingLeft: 40,
    paddingBottom: 10,
    alignSelf: 'center',
    backgroundColor: '#FBE069',
    color: 'black',
    outline: 'none',
    fontFamily: constants.FuturaMedium,
    fontSize: 18,
    textTransform: 'none',
  },
  lineItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  fieldName: {
    color: '#404040',
    fontSize: 20,
    fontFamily: constants.FuturaMedium,
    textAlign: 'right',
    paddingRight: 30,
  },
  waitfield: {
    color: '#707070',
    fontSize: 20,
    fontFamily: constants.FuturaMedium,
  },
  btnName: {
    color: '#404040',
    fontSize: 20,
    fontFamily: constants.FuturaMedium,
    paddingRight: 30,
  },
  fieldValue: { fontFamily: constants.FuturaBook, borderWidth: '1px' },
  error: {
    color: '#E44A4D',
    fontFamily: constants.FuturaBook,
  },
  formControlLabel: {
    fontSize: 8,
  },
  radioGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignSelf: 'center',
    marginLeft: -10,
  },
  radioFont: {
    fontSize: 12,
    fontFamily: constants.FuturaBook,
    textAlign: 'center',
  },
  fieldContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flexStart',
    marginBottom: 10,
  },
  datePicker: {
    borderBottom: '2px solid',
    color: '#D6D6D6',
    borderRight: 0,
    borderTop: 0,
    marginTop: -10,
    marginRight: 35,
    fontFamily: constants.FuturaBook,
    opacity: 0.5,
    outline: 'none',
    width: 150,
  },
  radioButton: {
    '&$checked': {
      color: '#4B8DF8',
    },
    checked: {},
    fontFamily: constants.FuturaBook,
    color: '#707070',
    fontSize: 18,
  },
  alignCenter: {
    display: 'flex',
    justifyContent: 'flex-start',
    marginTop: -20,
  },
  siteValue: {
    width: 335,
    fontFamily: constants.FuturaBook,
    backgroundColor: 'white',
    borderLeft: 0,
    borderRight: 0,
    borderTop: 0,
    marginLeft: 10,
  },
  pickerContainer: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: -15,
    marginRight: 30,
  },
  superText: {
    marginLeft: 3,
    marginBottom: 5,
    fontFamily: constants.FuturaBook,
    color: '#707070',
    fontSize: 10,
  },
  calendarContainer: {
    display: 'flex',
    flexDirection: 'column',
  },
  siteList: {
    fontFamily: constants.FuturaBook,
    width: 335,
    marginTop: -20,
    marginLeft: 10,
  },
  loadingPage: {
    fontFamily: constants.FuturaMedium,
    color: '#404040',
    fontSize: 20,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
  waitSubText: {
    color: '#707070',
    fontSize: 20,
    fontFamily: constants.FuturaMedium,
  },
  reportSubText: {
    fontFamily: constants.FuturaMedium,
    color: '#404040',
    fontSize: 20,
    marginTop: 30,
  },
  reportdownloadSubText: {
    fontFamily: constants.FuturaMedium,
    color: '#404040',
    fontSize: 26,
    marginTop: 30,
  },
  reportnewDownload: {
    fontFamily: constants.FuturaMedium,
    color: '#404040',
    fontSize: 20,
    marginTop: 10,
    textDecoration: 'underline',
  },
  calendar: {
    // marginLeft: -250,
    fontFamily: constants.FuturaBook,
    fontSize: 6,
    outline: 'none',
  },
};
export default styles;
